### ISSUE TITLE
Provider can not resolve sensitive data

### ISSUE THREAD

**Issue by benkeil** [cdk8s-team/cdk8s-cdktf-resolver#486]
### Description of the bug:

When `TerraformOutput` contains sensitive data, the resulting properties of the secret are omitted.

### Reproduction Steps:

```kotlin
DataKeepassEntry.Builder.create(this, "DataKeepassEntry_PAPERLESS_ADMIN_USER")
        .path("Root/PAPERLESS_ADMIN_USER")
        .build()
        .also {
          paperlessAdminUser =
              Fn.tostring(
                  TerraformOutput.Builder.create(this, "PAPERLESS_ADMIN_USER")
                      .value(it.password)
                      .sensitive(true)
                      .build()
                      .value)

...

Secret.Builder.create(this, "secret")
            .stringData(
                mapOf(
                    "PAPERLESS_SECRET_KEY" to config.paperlessSecretKey,
                    "PAPERLESS_ADMIN_USER" to config.paperlessAdminUser,
                    "PAPERLESS_ADMIN_PASSWORD" to config.paperlessAdminPassword,
                ))
            .build()
```

Result

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret-c89e4b62
  namespace: paperless
immutable: false
stringData: {}
```

### Environment:

  - **Framework Version**:
  - **OS**:

### Other:

---

This is :bug: Bug Report
